import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import Jogador from 'App/Models/Jogador'

export default class extends BaseSeeder {
  public async run () {
    await Jogador.createMany([
      {nome: "Saad Al Sheeb", camisa: 21, idade: 32, nacionalidade: "Catariano", selecaoId: 1, posicaoId: 1},
      {nome: "Pedro Miguel Carvalho Deus Correia", camisa: 2, idade: 32, nacionalidade: "Português", selecaoId: 1, posicaoId: 4},
      {nome: "Bassam Hisham Ali Al-Rawi", camisa: 5, idade: 24, nacionalidade: "Catariano", selecaoId: 1, posicaoId: 4},
      {nome: "Boualem Khoukhi", camisa: 16, idade: 32, nacionalidade: "Catariano", selecaoId: 1, posicaoId: 4},
      {nome: "Abdelkarim Hassan", camisa: 14, idade: 29, nacionalidade: "Catariano", selecaoId: 1, posicaoId: 3},
      {nome: "Karim Boudiaf", camisa: 12, idade: 32, nacionalidade: "Catariano", selecaoId: 1, posicaoId: 5},
      {nome: "Abdulaziz Hatem", camisa: 6, idade: 32, nacionalidade: "Catariano", selecaoId: 1, posicaoId: 6},
      {nome: "Ali Assadalla", camisa: 8, idade: 29, nacionalidade: "Catariano", selecaoId: 1, posicaoId: 6},
      {nome: "Akram Afif", camisa: 76, idade: 25, nacionalidade: "Catariano", selecaoId: 1, posicaoId: 7},
      {nome: "Ismaeel Mohammad", camisa: 7, idade: 32, nacionalidade: "Catariano", selecaoId: 1, posicaoId: 7},
      {nome: "Almoez Ali", camisa: 19, idade: 26, nacionalidade: "Catariano", selecaoId: 1, posicaoId: 7},
      {nome: "Alexander Domínguez", camisa: 22, idade: 35, nacionalidade: "Equatoriano", selecaoId: 2, posicaoId: 1},
      {nome: "Robert Abel Arboleda Escobar", camisa: 5, idade: 31, nacionalidade: "Equatoriano", selecaoId: 2, posicaoId: 4},
      {nome: "Xavier Arreaga", camisa: 3, idade: 28, nacionalidade: "Equatoriano", selecaoId: 2, posicaoId: 4},
      {nome: "Ángelo Smit Preciado Quiñónez", camisa: 77, idade: 24, nacionalidade: "Equatoriano", selecaoId: 2, posicaoId: 2},
      {nome: "Pervis Josué Estupiñán Tenorio", camisa: 30, idade: 24, nacionalidade: "Equatoriano", selecaoId: 2, posicaoId: 3},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},

    ])
  }
}
