import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import Jogador from 'App/Models/Jogador'

export default class extends BaseSeeder {
  public async run () {
    await Jogador.createMany([
      {nome: "Saad Al Sheeb", camisa: 21, idade: 32, nacionalidade: "Catariano", selecaoId: 1, posicaoId: 1},
      {nome: "Pedro Miguel Carvalho Deus Correia", camisa: 2, idade: 32, nacionalidade: "Português", selecaoId: 1, posicaoId: 4},
      {nome: "Bassam Hisham Ali Al-Rawi", camisa: 5, idade: 24, nacionalidade: "Catariano", selecaoId: 1, posicaoId: 4},
      {nome: "Boualem Khoukhi", camisa: 16, idade: 32, nacionalidade: "Catariano", selecaoId: 1, posicaoId: 4},
      {nome: "Abdelkarim Hassan", camisa: 14, idade: 29, nacionalidade: "Catariano", selecaoId: 1, posicaoId: 3},
      {nome: "Karim Boudiaf", camisa: 12, idade: 32, nacionalidade: "Catariano", selecaoId: 1, posicaoId: 5},
      {nome: "Abdulaziz Hatem", camisa: 6, idade: 32, nacionalidade: "Catariano", selecaoId: 1, posicaoId: 6},
      {nome: "Ali Assadalla", camisa: 8, idade: 29, nacionalidade: "Catariano", selecaoId: 1, posicaoId: 6},
      {nome: "Akram Afif", camisa: 76, idade: 25, nacionalidade: "Catariano", selecaoId: 1, posicaoId: 7},
      {nome: "Ismaeel Mohammad", camisa: 7, idade: 32, nacionalidade: "Catariano", selecaoId: 1, posicaoId: 7},
      {nome: "Almoez Ali", camisa: 19, idade: 26, nacionalidade: "Catariano", selecaoId: 1, posicaoId: 7},
      {nome: "Alexander Domínguez", camisa: 22, idade: 35, nacionalidade: "Equatoriano", selecaoId: 2, posicaoId: 1},
      {nome: "Robert Abel Arboleda Escobar", camisa: 5, idade: 31, nacionalidade: "Equatoriano", selecaoId: 2, posicaoId: 4},
      {nome: "Xavier Arreaga", camisa: 3, idade: 28, nacionalidade: "Equatoriano", selecaoId: 2, posicaoId: 4},
      {nome: "Ángelo Smit Preciado Quiñónez", camisa: 77, idade: 24, nacionalidade: "Equatoriano", selecaoId: 2, posicaoId: 2},
      {nome: "Pervis Josué Estupiñán Tenorio", camisa: 30, idade: 24, nacionalidade: "Equatoriano", selecaoId: 2, posicaoId: 3},
      {nome: "Carlos Armando Gruezo Arboleda", camisa: 8, idade: 27, nacionalidade: "Equatoriano", selecaoId: 2, posicaoId: 5},
      {nome: "Moisés Isaac Caicedo Corozo", camisa: 25, idade: 21, nacionalidade: "Equatoriano", selecaoId: 2, posicaoId: 6},
      {nome: "Enner Remberto Valencia Lastra", camisa: 13, idade: 33, nacionalidade: "Equatoriano", selecaoId: 2, posicaoId: 7},
      {nome: "Michael Steveen Estrada Martínez", camisa: 15, idade: 33, nacionalidade: "Equatoriano", selecaoId: 2, posicaoId: 7},
      {nome: "Édouard Osoque Mendy", camisa: 16, idade: 30, nacionalidade: "Franco Senegalês", selecaoId: 3, posicaoId: 1},
      {nome: "Seny Timothy Dieng", camisa: 1, idade: 27, nacionalidade: "Senegalês", selecaoId: 3, posicaoId: 1},
      {nome: "Kalidou Koulibaly", camisa: 26, idade: 31, nacionalidade: "Senegalês", selecaoId: 3, posicaoId: 4},
      {nome: "Abdou Diallo", camisa: 37, idade: 26, nacionalidade: "Senegalês", selecaoId: 3, posicaoId: 4},
      {nome: "Youssouf Sabaly", camisa: 23, idade: 29, nacionalidade: "Senegalês", selecaoId: 3, posicaoId: 2},
      {nome: "Fodé Ballo-Touré", camisa: 5, idade: 25, nacionalidade: "Senegalês", selecaoId: 3, posicaoId: 3},
      {nome: "Cheikhou Kouyaté", camisa: 19, idade: 32, nacionalidade: "Senegalês", selecaoId: 3, posicaoId: 5},
      {nome: "Nampalys Mendy", camisa: 24, idade: 30, nacionalidade: "Senegalês", selecaoId: 3, posicaoId: 5},
      {nome: "Famara Diedhiou", camisa: 14, idade: 29, nacionalidade: "Senegalês", selecaoId: 3, posicaoId: 7},
      {nome: "Cheikh Ahmadou Bamba Mbacke Dieng", camisa: 12, idade: 22, nacionalidade: "Senegalês", selecaoId: 3, posicaoId: 7},
      {nome: "Sadio Mané", camisa: 17, idade: 30, nacionalidade: "Senegalês", selecaoId: 3, posicaoId: 7},
      {nome: "Justin Bijlow", camisa: 1, idade: 24, nacionalidade: "Neerlandês", selecaoId: 4, posicaoId: 1},
      {nome: "Virgil van Dijk", camisa: 4, idade: 31, nacionalidade: "Neerlandês", selecaoId: 4, posicaoId: 4},
      {nome: "Nathan Benjamin Aké", camisa: 5, idade: 27, nacionalidade: "Neerlandês", selecaoId: 4, posicaoId: 4},
      {nome: "Matthijs de Ligt", camisa: 4, idade: 23, nacionalidade: "Neerlandês", selecaoId: 4, posicaoId: 4},
      {nome: "Frenkie de Jong", camisa: 21, idade: 25, nacionalidade: "Neerlandês", selecaoId: 4, posicaoId: 6},
      {nome: "Daley Blind", camisa: 17, idade: 32, nacionalidade: "Neerlandês", selecaoId: 4, posicaoId: 2 && 4},
      {nome: "Memphis Depay", camisa: 14, idade: 28, nacionalidade: "Neerlandês", selecaoId: 4, posicaoId: 7},
      {nome: "Wout Weghorst", camisa: 12, idade: 30, nacionalidade: "Neerlandês", selecaoId: 4, posicaoId: 7},
      {nome: "Jordan Lee Pickford", camisa: 1, idade: 28, nacionalidade: "Britânico", selecaoId: 5, posicaoId: 1},
      {nome: "Nicholas David Pope", camisa: 2, idade: 30, nacionalidade: "Inglês", selecaoId: 5, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},
      {nome: "", camisa: 10, idade: 28, nacionalidade: "", selecaoId: 1, posicaoId: 1},

    ])
  }
}
