import BaseSeeder from '@ioc:Adonis/Lucid/Seeder'
import Tecnico from 'App/Models/Tecnico'

export default class extends BaseSeeder {
  public async run () {
    await Tecnico.createMany([
      {
        id: 1,
        nome: "Aloysius Paulus Maria van Gaal",
        apelido: "Louis van Gaal",
        dataNascimento: new Date(1951, 8, 8),
        nacionalidade: "Neerlandês",
    },
      {
        id: 2,
        nome: "Gustavo Julio Alfaro",
        apelido: "Alfaro",
        dataNascimento: new Date(1962, 8, 14),
        nacionalidade: "Equatoriano",
    },
      {
        id: 3,
        nome: "Aliou Cissé",
        apelido: "Cisse",
        dataNascimento: new Date(1976, 3, 24),
        nacionalidade: "Senegalês",
    },
      {
        id: 4,
        nome: "Félix Sánchez Bas",
        apelido: "Bas",
        dataNascimento: new Date(1975, 12, 13),
        nacionalidade: "Espanhol",
    },
      {
        id: 5,
        nome: "Gareth Harold Southgate",
        apelido: "Gareth",
        dataNascimento: new Date(1970, 9, 3),
        nacionalidade: "Inglês",
    },
      {
        id: 6,
        nome: "Dragan Skočić",
        apelido: "Dragan",
        dataNascimento: new Date(1968, 9, 3),
        nacionalidade: "Croata",
    },
      {
        id: 7,
        nome: "Gregg Berhalter",
        apelido: "Gregg",
        dataNascimento: new Date(1973, 8, 1),
        nacionalidade: "Norte Americano",
    },
      {
        id: 8,
        nome: "Robert John Page",
        apelido: "Page",
        dataNascimento: new Date(1974, 9, 3),
        nacionalidade: "Galês",
    },
      {
        id: 9,
        nome: "Czesław Michniewicz",
        apelido: "Czesław",
        dataNascimento: new Date(1970, 2, 12),
        nacionalidade: "Polonês",
    },
      {
        id: 10,
        nome: "Lionel Sebastián Scaloni",
        apelido: "Sebastian",
        dataNascimento: new Date(1978, 5, 16),
        nacionalidade: "Argentino",
    },
      {
        id: 11,
        nome: "Hervé Renard",
        apelido: "Renard",
        dataNascimento: new Date(1968, 9, 30),
        nacionalidade: "Francês",
    },
      {
        id: 12,
        nome: "Gerardo Daniel Martino",
        apelido: "Tata Martino",
        dataNascimento: new Date(1962, 11, 20),
        nacionalidade: "Argentino",
    },
      {
        id: 13,
        nome: "Didier Claude Deschamps",
        apelido: "Deschamps",
        dataNascimento: new Date(1968, 10, 15),
        nacionalidade: "Francês",
    },
      {
        id: 14,
        nome: "Graham Arnold",
        apelido: "Arnold",
        dataNascimento: new Date(1963, 8, 3),
        nacionalidade: "Australiano",
    },
      {
        id: 15,
        nome: "Kasper Hjulmand",
        apelido: "Kasper",
        dataNascimento: new Date(1972, 4, 9),
        nacionalidade: "Dinamarquês",
    },
      {
        id: 16,
        nome: "Jalel Kadri",
        apelido: "Kadri",
        dataNascimento: new Date(1971, 12, 14),
        nacionalidade: "Tunisiano",
    },
      {
        id: 17,
        nome: "Luis Enrique Martínez García",
        apelido: "Martinez",
        dataNascimento: new Date(1970, 5, 8),
        nacionalidade: "Espanhol",
    },
      {
        id: 18,
        nome: "Hajime Moriyasu",
        apelido: "Hajime",
        dataNascimento: new Date(1968, 8, 23),
        nacionalidade: "Japonês",
    },
      {
        id: 19,
        nome: "Luis Fernando Suárez Guzmán",
        apelido: "Suaréz",
        dataNascimento: new Date(1959, 12, 23),
        nacionalidade: "Colombiano",
    },
      {
        id: 20,
        nome: "Hans-Dieter Flick",
        apelido: "Hansi",
        dataNascimento: new Date(1965, 2, 24),
        nacionalidade: "Alemão",
    },
      {
        id: 21,
        nome: "Zlatko Dalić",
        apelido: "Dalic",
        dataNascimento: new Date(1966, 10, 26),
        nacionalidade: "Croata",
    },
      {
        id: 22,
        nome: "Vahid Halilhodžić",
        apelido: "Vahid",
        dataNascimento: new Date(1952, 10, 15),
        nacionalidade: "Bósnio",
    },
      {
        id: 23,
        nome: "Roberto Martínez Montoliu",
        apelido: "Montoliu",
        dataNascimento: new Date(1973, 7, 13),
        nacionalidade: "Espanhol",
    },
      {
        id: 24,
        nome: "John Herdman",
        apelido: "John",
        dataNascimento: new Date(1975, 7, 19),
        nacionalidade: "Canadense",
    },
      {
        id: 25,
        nome: "	Adenor Leonardo Bachi",
        apelido: "Tite",
        dataNascimento: new Date(1961, 5, 25),
        nacionalidade: "Brasileiro",
    },
      {
        id: 26,
        nome: "Murat Yakin",
        apelido: "Yakin",
        dataNascimento: new Date(1974, 9, 15),
        nacionalidade: "Suíço",
    },
      {
        id: 27,
        nome: "Rigobert Song Bahanag",
        apelido: "Bahanag",
        dataNascimento: new Date(1976, 7, 1),
        nacionalidade: "Camaronês",
    },
      {
        id: 28,
        nome: "Dragan Stojković",
        apelido: "Stojkovic",
        dataNascimento: new Date(1965, 3, 3),
        nacionalidade: "Sérvio",
    },
      {
        id: 29,
        nome: "	Fernando Manuel Fernandes da Costa Santos",
        apelido: "Fernando Santos",
        dataNascimento: new Date(1954, 10, 10),
        nacionalidade: "Português",
    },
      {
        id: 30,
        nome: "Paulo Jorge Gomes Bento",
        apelido: "Bento",
        dataNascimento: new Date(1969, 6, 20),
        nacionalidade: "Português",
    },
      {
        id: 31,
        nome: "Diego Martín Alonso López",
        apelido: "Alonso",
        dataNascimento: new Date(1975, 4, 16),
        nacionalidade: "Uruguaio",
    },
      {
        id: 32,
        nome: "Otto Addo",
        apelido: "Otto",
        dataNascimento: new Date(1975, 6, 9),
        nacionalidade: "Alemão Ganês",
    },
    ])
  }
}
